Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -25,8 +25,8 @@ jobs:
             exit 1
           )
 
-          test -f cover.jpg || (
-            echo "ERROR: cover.jpg not found!"
+          test -f "20261007_183847.jpg" || (
+            echo "ERROR: cover image not found!"
             exit 1
           )
 
@@ -58,7 +58,9 @@ jobs:
           mkdir -p app/src/main/res/values
 
           cp index.html app/src/main/assets/index.html
-          cp cover.jpg app/src/main/assets/cover.jpg
+
+          cp "20261007_183847.jpg" \
+             app/src/main/assets/cover.jpg
 
           cat > settings.gradle <<'EOF'
           pluginManagement {
